language: node_js
node_js: stable

deploy:
  provider: pages
  skip-cleanup: true
  github-token: ${GITHUB_TOKEN}  # Set in travis-ci.org dashboard, marked secure
  local-dir: _book
  target-branch: gh-pages
  keep-history: false
  verbose: true
  on:
    branch: master

cache:
  directories:
  - node_modules

script:
  - npm run build

branches:
  only:
    - master
